### PR TITLE
ci(cu-caterpillar): add determinism record/resim test

### LINKED ISSUE #728: add a deterministic non-regression test in CI
we drifted from determinism until I realized it testing it manually, let's add that in CI because it is very fragile.

### PR DESCRIPTION
**Pull request by makeecat**
## Summary
- Add a determinism contract test for the `cu-caterpillar` example, gated behind a new `determinism_ci` feature.
- Wire the determinism test into CI (debug workspace only) and into `just std-ci` for local runs.
## Related issues
- Closes #728 

## Changes
  - New determinism test builds a sim-mode app, records two runs, replays `copperlists`, and compares `bincode-encoded` streams to enforce `record/resim` equality; it writes under `target/determinism_tests` and cleans up on success.
  - `examples/cu_caterpillar/Cargo.toml` adds `determinism_ci`, and `examples/cu_caterpillar/src/main.rs` conditionally includes the test module under `#[cfg(all(test, feature = "determinism_ci"))]`.
  - CI and `justfile` run the test single-threaded with fixed env `(RAYON_NUM_THREADS=1, COPPER_DETERMINISM_ITERS=256,COPPER_DETERMINISM_DT_TICKS=1000)` for stability.
## Testing
- [x] `just std-ci`
- [x] `just lint`
- [x] `cargo +stable nextest run --workspace --all-targets`
- [x] `RAYON_NUM_THREADS=1 COPPER_DETERMINISM_ITERS=32 COPPER_DETERMINISM_DT_TICKS=1000 cargo test -p cu-caterpillar --features determinism_ci -- determinism_record_and_resim --test-threads=1`

## Checklist
- [x] I have updated docs or examples where needed
- [x] I have added or updated tests where needed
- [x] I have considered platform impact (Linux/macOS/Windows/embedded)
- [x] I have considered config/logging changes (if applicable)
- [x] This change is not a breaking change (or I documented it below)

### CODE REVIEW

File: examples/cu_caterpillar/src/determinism_test.rs [hunk 1]
```diff
@@ -0,0 +1,315 @@
...
+
+    // 2) A == B
+    assert_streams_equal("record_a", &a_stream, "record_b", &b_stream);
+
+    // 3) resim(A)
+    resim_run(&a_base, &r_base).expect("resim(A) failed");
+    let r_stream = read_copperlist_stream_encoded(&r_base).expect("read resim failed");
+
+    // 4) A == resim(A)
+    assert_streams_equal("record_a", &a_stream, "resim_a", &r_stream);
```
Comment (gbin) [inline examples/cu_caterpillar/src/determinism_test.rs:342]: should the keyframes tested too?

Comment (makeecat) [reply examples/cu_caterpillar/src/determinism_test.rs:342]: 1. Switched determinism test to a test-specific config
2. Added keyframe test

**Review by gbin — APPROVED** [review]
