### PR TITLE
fix: make GPIO slots configurable

### LINKED ISSUE #811: bug: GPIOs on the linux bundle are too rigid
## Steps to reproduce
I might want a GPIO with a pull-up. Or a GPIO that is both in-out with a pull-up pull-down etc... 

## Expected behavior

I think the direction should be a parameter + inspect the linux API for gpio and add the correct parameters.
https://www.kernel.org/doc/html/latest/driver-api/gpio/

## Environment
- Copper revision (commit SHA, tag, or branch): master
- Operating system (optional): linux

### PR DESCRIPTION
**Pull request by makeecat**
## Summary

Refactors Linux GPIO resources to use direction-agnostic slots (gpio0..gpio5) with per-slot configuration (pin, direction, bias, initial_level) instead of separate gpio_out*/gpio_in* slots. It also updates runtime slot rendering and related docs/examples to match.
## Related issues
- Closes #811 
## Changes
- `components/res/cu_linux_resources/src/lib.rs`: replaced `gpio_out0..2` and `gpio_in0..2` with `gpio0..5`.
- `components/res/cu_linux_resources/src/lib.rs`: added per-slot config keys `gpioN_pin`, `gpioN_direction`, optional `gpioN_bias`, and optional `gpioN_initial_level`.
- c`omponents/res/cu_linux_resources/src/lib.rs`: changed output pin handling to `IoPin`, applies bias for input/output, and sets output initial level during initialization.
- `components/res/cu_linux_resources/src/lib.rs`: added strict validation/parsing for GPIO direction/bias/initial-level and added unit tests for parser/validation behavior.
- `core/cu29_runtime/src/rendercfg.rs`: updated Linux resource slot names in render output to `gpio0..gpio5`.
- `components/res/cu_linux_resources/README.md`: updated GPIO docs and examples for the new slot model and validation rules.
- `components/sinks/cu_rp_gpio/src/lib.rs` and `components/sinks/cu_rp_gpio/README.md`: updated resource binding examples to gpio0.
- `components/sources/cu_rp_encoder/README.md`: updated example config/bindings to gpio0/gpio1 with explicit input direction.

## Testing
- [x] `just std-ci`
- [x] `just lint`
- [x] `cargo +stable nextest run --workspace --all-targets`

## Checklist
- [x] I have updated docs or examples where needed
- [x] I have added or updated tests where needed
- [x] I have considered platform impact (Linux/macOS/Windows/embedded)
- [x] I have considered config/logging changes (if applicable)
- [x] This change is not a breaking change (or I documented it below)

### CODE REVIEW

File: components/res/cu_linux_resources/src/lib.rs [hunk 1]
```diff
@@ -294,30 +294,17 @@ bundle_resources!(
...
-    "i2c0",
-    "i2c1",
-    "i2c2",
-    "gpio_out0",
-    "gpio_out1",
-    "gpio_out2",
-    "gpio_in0",
-    "gpio_in1",
-    "gpio_in2",
+    "serial0", "serial1", "serial2", "serial3", "serial4", "serial5", "i2c0", "i2c1", "i2c2",
```
Comment (gbin) [inline components/res/cu_linux_resources/src/lib.rs]: this became inconsistent.

File: components/res/cu_linux_resources/src/lib.rs [hunk 2]
```diff
@@ -411,38 +398,107 @@ const I2C_SLOTS: &[I2cSlot] = &[
...
-        id: LinuxResourcesId::GpioIn1,
-        key: GPIO_IN1_PIN_KEY,
+        id: LinuxResourcesId::Gpio4,
+        name: GPIO4_NAME,
+        pin_key: "gpio4_pin",
+        direction_key: "gpio4_direction",
+        bias_key: "gpio4_bias",
+        initial_level_key: "gpio4_initial_level",
     },
     GpioSlot {
```
Comment (gbin) [inline components/res/cu_linux_resources/src/lib.rs]: Can we macro ourselves out of the copy pasting?

File: components/res/cu_linux_resources/src/lib.rs (hunk 1 above)
Comment (makeecat) [reply components/res/cu_linux_resources/src/lib.rs]: can you elaborate? from formatting perspective or naming style perspective

Comment (gbin) [reply components/res/cu_linux_resources/src/lib.rs]: no constants for some names, strings for others

File: components/res/cu_linux_resources/src/lib.rs [hunk 3]
```diff
@@ -600,6 +639,60 @@ fn read_serial_slot_config(
...
+
+    let bias = match bias {
+        Some(raw) => parse_gpio_bias_value(raw.as_str())?,
+        None => GpioBias::Off,
+    };
+
+    let has_initial_level = initial_level.is_some();
+    let initial_level = match initial_level {
+        Some(raw) => parse_gpio_initial_level_value(raw.as_str())?,
+        None => GpioInitialLevel::Low,
```
[the remark this answers is not in the document]
Comment (makeecat) [reply components/res/cu_linux_resources/src/lib.rs]: Fixed default GPIO behavior so unset gpioN_initial_level preserves current output level

File: components/res/cu_linux_resources/src/lib.rs (hunk 1 above)
Comment (makeecat) [reply components/res/cu_linux_resources/src/lib.rs]: Addressed inconsistency by replacing mixed string literals/constants with named constants for slot names and GPIO keys

File: components/res/cu_linux_resources/src/lib.rs (hunk 2 above)
Comment (makeecat) [reply components/res/cu_linux_resources/src/lib.rs]: Replaced repetitive GPIO slot struct literals with a macro-based declaration
